#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciBilgiSistemi.Fonksiyonlar
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OgrenciIsleriSistemi")]
	public partial class ogrenciIsleriDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblBolum(tblBolum instance);
    partial void UpdatetblBolum(tblBolum instance);
    partial void DeletetblBolum(tblBolum instance);
    partial void InserttblDersKayit(tblDersKayit instance);
    partial void UpdatetblDersKayit(tblDersKayit instance);
    partial void DeletetblDersKayit(tblDersKayit instance);
    partial void InserttblDersSecim(tblDersSecim instance);
    partial void UpdatetblDersSecim(tblDersSecim instance);
    partial void DeletetblDersSecim(tblDersSecim instance);
    partial void InserttblFakulte(tblFakulte instance);
    partial void UpdatetblFakulte(tblFakulte instance);
    partial void DeletetblFakulte(tblFakulte instance);
    partial void InserttblGiri(tblGiri instance);
    partial void UpdatetblGiri(tblGiri instance);
    partial void DeletetblGiri(tblGiri instance);
    partial void InserttblMode(tblMode instance);
    partial void UpdatetblMode(tblMode instance);
    partial void DeletetblMode(tblMode instance);
    partial void InserttblOgrenci(tblOgrenci instance);
    partial void UpdatetblOgrenci(tblOgrenci instance);
    partial void DeletetblOgrenci(tblOgrenci instance);
    partial void InserttblOgrtGorevlisi(tblOgrtGorevlisi instance);
    partial void UpdatetblOgrtGorevlisi(tblOgrtGorevlisi instance);
    partial void DeletetblOgrtGorevlisi(tblOgrtGorevlisi instance);
    #endregion
		
		public ogrenciIsleriDataContext() : 
				base(global::OgrenciBilgiSistemi.Properties.Settings.Default.OgrenciIsleriSistemiConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ogrenciIsleriDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ogrenciIsleriDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ogrenciIsleriDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ogrenciIsleriDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblBolum> tblBolums
		{
			get
			{
				return this.GetTable<tblBolum>();
			}
		}
		
		public System.Data.Linq.Table<tblDersKayit> tblDersKayits
		{
			get
			{
				return this.GetTable<tblDersKayit>();
			}
		}
		
		public System.Data.Linq.Table<tblDersSecim> tblDersSecims
		{
			get
			{
				return this.GetTable<tblDersSecim>();
			}
		}
		
		public System.Data.Linq.Table<tblFakulte> tblFakultes
		{
			get
			{
				return this.GetTable<tblFakulte>();
			}
		}
		
		public System.Data.Linq.Table<tblGiri> tblGiris
		{
			get
			{
				return this.GetTable<tblGiri>();
			}
		}
		
		public System.Data.Linq.Table<tblMode> tblModes
		{
			get
			{
				return this.GetTable<tblMode>();
			}
		}
		
		public System.Data.Linq.Table<tblOgrenci> tblOgrencis
		{
			get
			{
				return this.GetTable<tblOgrenci>();
			}
		}
		
		public System.Data.Linq.Table<tblOgrtGorevlisi> tblOgrtGorevlisis
		{
			get
			{
				return this.GetTable<tblOgrtGorevlisi>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblBolum")]
	public partial class tblBolum : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _BolumAdi;
		
		private System.Nullable<int> _FakulteId;
		
		private EntitySet<tblDersKayit> _tblDersKayits;
		
		private EntitySet<tblDersSecim> _tblDersSecims;
		
		private EntitySet<tblOgrenci> _tblOgrencis;
		
		private EntityRef<tblFakulte> _tblFakulte;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnBolumAdiChanging(string value);
    partial void OnBolumAdiChanged();
    partial void OnFakulteIdChanging(System.Nullable<int> value);
    partial void OnFakulteIdChanged();
    #endregion
		
		public tblBolum()
		{
			this._tblDersKayits = new EntitySet<tblDersKayit>(new Action<tblDersKayit>(this.attach_tblDersKayits), new Action<tblDersKayit>(this.detach_tblDersKayits));
			this._tblDersSecims = new EntitySet<tblDersSecim>(new Action<tblDersSecim>(this.attach_tblDersSecims), new Action<tblDersSecim>(this.detach_tblDersSecims));
			this._tblOgrencis = new EntitySet<tblOgrenci>(new Action<tblOgrenci>(this.attach_tblOgrencis), new Action<tblOgrenci>(this.detach_tblOgrencis));
			this._tblFakulte = default(EntityRef<tblFakulte>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BolumAdi", DbType="NVarChar(150)")]
		public string BolumAdi
		{
			get
			{
				return this._BolumAdi;
			}
			set
			{
				if ((this._BolumAdi != value))
				{
					this.OnBolumAdiChanging(value);
					this.SendPropertyChanging();
					this._BolumAdi = value;
					this.SendPropertyChanged("BolumAdi");
					this.OnBolumAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FakulteId", DbType="Int")]
		public System.Nullable<int> FakulteId
		{
			get
			{
				return this._FakulteId;
			}
			set
			{
				if ((this._FakulteId != value))
				{
					if (this._tblFakulte.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFakulteIdChanging(value);
					this.SendPropertyChanging();
					this._FakulteId = value;
					this.SendPropertyChanged("FakulteId");
					this.OnFakulteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblBolum_tblDersKayit", Storage="_tblDersKayits", ThisKey="Id", OtherKey="BolumId")]
		public EntitySet<tblDersKayit> tblDersKayits
		{
			get
			{
				return this._tblDersKayits;
			}
			set
			{
				this._tblDersKayits.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblBolum_tblDersSecim", Storage="_tblDersSecims", ThisKey="Id", OtherKey="BolumId")]
		public EntitySet<tblDersSecim> tblDersSecims
		{
			get
			{
				return this._tblDersSecims;
			}
			set
			{
				this._tblDersSecims.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblBolum_tblOgrenci", Storage="_tblOgrencis", ThisKey="Id", OtherKey="BolumId")]
		public EntitySet<tblOgrenci> tblOgrencis
		{
			get
			{
				return this._tblOgrencis;
			}
			set
			{
				this._tblOgrencis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblFakulte_tblBolum", Storage="_tblFakulte", ThisKey="FakulteId", OtherKey="Id", IsForeignKey=true)]
		public tblFakulte tblFakulte
		{
			get
			{
				return this._tblFakulte.Entity;
			}
			set
			{
				tblFakulte previousValue = this._tblFakulte.Entity;
				if (((previousValue != value) 
							|| (this._tblFakulte.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblFakulte.Entity = null;
						previousValue.tblBolums.Remove(this);
					}
					this._tblFakulte.Entity = value;
					if ((value != null))
					{
						value.tblBolums.Add(this);
						this._FakulteId = value.Id;
					}
					else
					{
						this._FakulteId = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblFakulte");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblDersKayits(tblDersKayit entity)
		{
			this.SendPropertyChanging();
			entity.tblBolum = this;
		}
		
		private void detach_tblDersKayits(tblDersKayit entity)
		{
			this.SendPropertyChanging();
			entity.tblBolum = null;
		}
		
		private void attach_tblDersSecims(tblDersSecim entity)
		{
			this.SendPropertyChanging();
			entity.tblBolum = this;
		}
		
		private void detach_tblDersSecims(tblDersSecim entity)
		{
			this.SendPropertyChanging();
			entity.tblBolum = null;
		}
		
		private void attach_tblOgrencis(tblOgrenci entity)
		{
			this.SendPropertyChanging();
			entity.tblBolum = this;
		}
		
		private void detach_tblOgrencis(tblOgrenci entity)
		{
			this.SendPropertyChanging();
			entity.tblBolum = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDersKayit")]
	public partial class tblDersKayit : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _DersAdi;
		
		private System.Nullable<int> _BolumId;
		
		private System.Nullable<int> _OgrtId;
		
		private EntitySet<tblDersSecim> _tblDersSecims;
		
		private EntityRef<tblBolum> _tblBolum;
		
		private EntityRef<tblOgrtGorevlisi> _tblOgrtGorevlisi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDersAdiChanging(string value);
    partial void OnDersAdiChanged();
    partial void OnBolumIdChanging(System.Nullable<int> value);
    partial void OnBolumIdChanged();
    partial void OnOgrtIdChanging(System.Nullable<int> value);
    partial void OnOgrtIdChanged();
    #endregion
		
		public tblDersKayit()
		{
			this._tblDersSecims = new EntitySet<tblDersSecim>(new Action<tblDersSecim>(this.attach_tblDersSecims), new Action<tblDersSecim>(this.detach_tblDersSecims));
			this._tblBolum = default(EntityRef<tblBolum>);
			this._tblOgrtGorevlisi = default(EntityRef<tblOgrtGorevlisi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DersAdi", DbType="NVarChar(100)")]
		public string DersAdi
		{
			get
			{
				return this._DersAdi;
			}
			set
			{
				if ((this._DersAdi != value))
				{
					this.OnDersAdiChanging(value);
					this.SendPropertyChanging();
					this._DersAdi = value;
					this.SendPropertyChanged("DersAdi");
					this.OnDersAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BolumId", DbType="Int")]
		public System.Nullable<int> BolumId
		{
			get
			{
				return this._BolumId;
			}
			set
			{
				if ((this._BolumId != value))
				{
					if (this._tblBolum.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBolumIdChanging(value);
					this.SendPropertyChanging();
					this._BolumId = value;
					this.SendPropertyChanged("BolumId");
					this.OnBolumIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OgrtId", DbType="Int")]
		public System.Nullable<int> OgrtId
		{
			get
			{
				return this._OgrtId;
			}
			set
			{
				if ((this._OgrtId != value))
				{
					if (this._tblOgrtGorevlisi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnOgrtIdChanging(value);
					this.SendPropertyChanging();
					this._OgrtId = value;
					this.SendPropertyChanged("OgrtId");
					this.OnOgrtIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDersKayit_tblDersSecim", Storage="_tblDersSecims", ThisKey="Id", OtherKey="DersId")]
		public EntitySet<tblDersSecim> tblDersSecims
		{
			get
			{
				return this._tblDersSecims;
			}
			set
			{
				this._tblDersSecims.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblBolum_tblDersKayit", Storage="_tblBolum", ThisKey="BolumId", OtherKey="Id", IsForeignKey=true)]
		public tblBolum tblBolum
		{
			get
			{
				return this._tblBolum.Entity;
			}
			set
			{
				tblBolum previousValue = this._tblBolum.Entity;
				if (((previousValue != value) 
							|| (this._tblBolum.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblBolum.Entity = null;
						previousValue.tblDersKayits.Remove(this);
					}
					this._tblBolum.Entity = value;
					if ((value != null))
					{
						value.tblDersKayits.Add(this);
						this._BolumId = value.Id;
					}
					else
					{
						this._BolumId = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblBolum");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblOgrtGorevlisi_tblDersKayit", Storage="_tblOgrtGorevlisi", ThisKey="OgrtId", OtherKey="Id", IsForeignKey=true)]
		public tblOgrtGorevlisi tblOgrtGorevlisi
		{
			get
			{
				return this._tblOgrtGorevlisi.Entity;
			}
			set
			{
				tblOgrtGorevlisi previousValue = this._tblOgrtGorevlisi.Entity;
				if (((previousValue != value) 
							|| (this._tblOgrtGorevlisi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblOgrtGorevlisi.Entity = null;
						previousValue.tblDersKayits.Remove(this);
					}
					this._tblOgrtGorevlisi.Entity = value;
					if ((value != null))
					{
						value.tblDersKayits.Add(this);
						this._OgrtId = value.Id;
					}
					else
					{
						this._OgrtId = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblOgrtGorevlisi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblDersSecims(tblDersSecim entity)
		{
			this.SendPropertyChanging();
			entity.tblDersKayit = this;
		}
		
		private void detach_tblDersSecims(tblDersSecim entity)
		{
			this.SendPropertyChanging();
			entity.tblDersKayit = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDersSecim")]
	public partial class tblDersSecim : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _DersId;
		
		private System.Nullable<int> _OgrId;
		
		private System.Nullable<int> _BolumId;
		
		private EntityRef<tblBolum> _tblBolum;
		
		private EntityRef<tblDersKayit> _tblDersKayit;
		
		private EntityRef<tblOgrenci> _tblOgrenci;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDersIdChanging(System.Nullable<int> value);
    partial void OnDersIdChanged();
    partial void OnOgrIdChanging(System.Nullable<int> value);
    partial void OnOgrIdChanged();
    partial void OnBolumIdChanging(System.Nullable<int> value);
    partial void OnBolumIdChanged();
    #endregion
		
		public tblDersSecim()
		{
			this._tblBolum = default(EntityRef<tblBolum>);
			this._tblDersKayit = default(EntityRef<tblDersKayit>);
			this._tblOgrenci = default(EntityRef<tblOgrenci>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DersId", DbType="Int")]
		public System.Nullable<int> DersId
		{
			get
			{
				return this._DersId;
			}
			set
			{
				if ((this._DersId != value))
				{
					if (this._tblDersKayit.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDersIdChanging(value);
					this.SendPropertyChanging();
					this._DersId = value;
					this.SendPropertyChanged("DersId");
					this.OnDersIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OgrId", DbType="Int")]
		public System.Nullable<int> OgrId
		{
			get
			{
				return this._OgrId;
			}
			set
			{
				if ((this._OgrId != value))
				{
					if (this._tblOgrenci.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnOgrIdChanging(value);
					this.SendPropertyChanging();
					this._OgrId = value;
					this.SendPropertyChanged("OgrId");
					this.OnOgrIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BolumId", DbType="Int")]
		public System.Nullable<int> BolumId
		{
			get
			{
				return this._BolumId;
			}
			set
			{
				if ((this._BolumId != value))
				{
					if (this._tblBolum.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBolumIdChanging(value);
					this.SendPropertyChanging();
					this._BolumId = value;
					this.SendPropertyChanged("BolumId");
					this.OnBolumIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblBolum_tblDersSecim", Storage="_tblBolum", ThisKey="BolumId", OtherKey="Id", IsForeignKey=true)]
		public tblBolum tblBolum
		{
			get
			{
				return this._tblBolum.Entity;
			}
			set
			{
				tblBolum previousValue = this._tblBolum.Entity;
				if (((previousValue != value) 
							|| (this._tblBolum.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblBolum.Entity = null;
						previousValue.tblDersSecims.Remove(this);
					}
					this._tblBolum.Entity = value;
					if ((value != null))
					{
						value.tblDersSecims.Add(this);
						this._BolumId = value.Id;
					}
					else
					{
						this._BolumId = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblBolum");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDersKayit_tblDersSecim", Storage="_tblDersKayit", ThisKey="DersId", OtherKey="Id", IsForeignKey=true)]
		public tblDersKayit tblDersKayit
		{
			get
			{
				return this._tblDersKayit.Entity;
			}
			set
			{
				tblDersKayit previousValue = this._tblDersKayit.Entity;
				if (((previousValue != value) 
							|| (this._tblDersKayit.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblDersKayit.Entity = null;
						previousValue.tblDersSecims.Remove(this);
					}
					this._tblDersKayit.Entity = value;
					if ((value != null))
					{
						value.tblDersSecims.Add(this);
						this._DersId = value.Id;
					}
					else
					{
						this._DersId = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblDersKayit");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblOgrenci_tblDersSecim", Storage="_tblOgrenci", ThisKey="OgrId", OtherKey="Id", IsForeignKey=true)]
		public tblOgrenci tblOgrenci
		{
			get
			{
				return this._tblOgrenci.Entity;
			}
			set
			{
				tblOgrenci previousValue = this._tblOgrenci.Entity;
				if (((previousValue != value) 
							|| (this._tblOgrenci.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblOgrenci.Entity = null;
						previousValue.tblDersSecims.Remove(this);
					}
					this._tblOgrenci.Entity = value;
					if ((value != null))
					{
						value.tblDersSecims.Add(this);
						this._OgrId = value.Id;
					}
					else
					{
						this._OgrId = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblOgrenci");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblFakulte")]
	public partial class tblFakulte : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _FakulteAdi;
		
		private EntitySet<tblBolum> _tblBolums;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFakulteAdiChanging(string value);
    partial void OnFakulteAdiChanged();
    #endregion
		
		public tblFakulte()
		{
			this._tblBolums = new EntitySet<tblBolum>(new Action<tblBolum>(this.attach_tblBolums), new Action<tblBolum>(this.detach_tblBolums));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FakulteAdi", DbType="NVarChar(150)")]
		public string FakulteAdi
		{
			get
			{
				return this._FakulteAdi;
			}
			set
			{
				if ((this._FakulteAdi != value))
				{
					this.OnFakulteAdiChanging(value);
					this.SendPropertyChanging();
					this._FakulteAdi = value;
					this.SendPropertyChanged("FakulteAdi");
					this.OnFakulteAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblFakulte_tblBolum", Storage="_tblBolums", ThisKey="Id", OtherKey="FakulteId")]
		public EntitySet<tblBolum> tblBolums
		{
			get
			{
				return this._tblBolums;
			}
			set
			{
				this._tblBolums.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblBolums(tblBolum entity)
		{
			this.SendPropertyChanging();
			entity.tblFakulte = this;
		}
		
		private void detach_tblBolums(tblBolum entity)
		{
			this.SendPropertyChanging();
			entity.tblFakulte = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblGiris")]
	public partial class tblGiri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _kullaniciAdi;
		
		private string _sifre;
		
		private System.Nullable<int> _mode;
		
		private EntityRef<tblMode> _tblMode;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnkullaniciAdiChanging(string value);
    partial void OnkullaniciAdiChanged();
    partial void OnsifreChanging(string value);
    partial void OnsifreChanged();
    partial void OnmodeChanging(System.Nullable<int> value);
    partial void OnmodeChanged();
    #endregion
		
		public tblGiri()
		{
			this._tblMode = default(EntityRef<tblMode>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kullaniciAdi", DbType="NVarChar(150)")]
		public string kullaniciAdi
		{
			get
			{
				return this._kullaniciAdi;
			}
			set
			{
				if ((this._kullaniciAdi != value))
				{
					this.OnkullaniciAdiChanging(value);
					this.SendPropertyChanging();
					this._kullaniciAdi = value;
					this.SendPropertyChanged("kullaniciAdi");
					this.OnkullaniciAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sifre", DbType="NVarChar(50)")]
		public string sifre
		{
			get
			{
				return this._sifre;
			}
			set
			{
				if ((this._sifre != value))
				{
					this.OnsifreChanging(value);
					this.SendPropertyChanging();
					this._sifre = value;
					this.SendPropertyChanged("sifre");
					this.OnsifreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mode", DbType="Int")]
		public System.Nullable<int> mode
		{
			get
			{
				return this._mode;
			}
			set
			{
				if ((this._mode != value))
				{
					if (this._tblMode.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmodeChanging(value);
					this.SendPropertyChanging();
					this._mode = value;
					this.SendPropertyChanged("mode");
					this.OnmodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMode_tblGiri", Storage="_tblMode", ThisKey="mode", OtherKey="id", IsForeignKey=true)]
		public tblMode tblMode
		{
			get
			{
				return this._tblMode.Entity;
			}
			set
			{
				tblMode previousValue = this._tblMode.Entity;
				if (((previousValue != value) 
							|| (this._tblMode.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblMode.Entity = null;
						previousValue.tblGiris.Remove(this);
					}
					this._tblMode.Entity = value;
					if ((value != null))
					{
						value.tblGiris.Add(this);
						this._mode = value.id;
					}
					else
					{
						this._mode = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblMode");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblMode")]
	public partial class tblMode : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _modeAdları;
		
		private EntitySet<tblGiri> _tblGiris;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmodeAdlarıChanging(string value);
    partial void OnmodeAdlarıChanged();
    #endregion
		
		public tblMode()
		{
			this._tblGiris = new EntitySet<tblGiri>(new Action<tblGiri>(this.attach_tblGiris), new Action<tblGiri>(this.detach_tblGiris));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modeAdları", DbType="NVarChar(50)")]
		public string modeAdları
		{
			get
			{
				return this._modeAdları;
			}
			set
			{
				if ((this._modeAdları != value))
				{
					this.OnmodeAdlarıChanging(value);
					this.SendPropertyChanging();
					this._modeAdları = value;
					this.SendPropertyChanged("modeAdları");
					this.OnmodeAdlarıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMode_tblGiri", Storage="_tblGiris", ThisKey="id", OtherKey="mode")]
		public EntitySet<tblGiri> tblGiris
		{
			get
			{
				return this._tblGiris;
			}
			set
			{
				this._tblGiris.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblGiris(tblGiri entity)
		{
			this.SendPropertyChanging();
			entity.tblMode = this;
		}
		
		private void detach_tblGiris(tblGiri entity)
		{
			this.SendPropertyChanging();
			entity.tblMode = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblOgrenci")]
	public partial class tblOgrenci : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _OgrAdiSoyadi;
		
		private string _OgrNumara;
		
		private string _TcKimlik;
		
		private string _Email;
		
		private System.Nullable<int> _BolumId;
		
		private string _Adres;
		
		private string _Telefon;
		
		private System.Nullable<System.DateTime> _DogumTarihi;
		
		private System.Data.Linq.Binary _Resim;
		
		private System.Nullable<System.DateTime> _KayıtTarihi;
		
		private EntitySet<tblDersSecim> _tblDersSecims;
		
		private EntityRef<tblBolum> _tblBolum;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnOgrAdiSoyadiChanging(string value);
    partial void OnOgrAdiSoyadiChanged();
    partial void OnOgrNumaraChanging(string value);
    partial void OnOgrNumaraChanged();
    partial void OnTcKimlikChanging(string value);
    partial void OnTcKimlikChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnBolumIdChanging(System.Nullable<int> value);
    partial void OnBolumIdChanged();
    partial void OnAdresChanging(string value);
    partial void OnAdresChanged();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    partial void OnDogumTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnDogumTarihiChanged();
    partial void OnResimChanging(System.Data.Linq.Binary value);
    partial void OnResimChanged();
    partial void OnKayıtTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnKayıtTarihiChanged();
    #endregion
		
		public tblOgrenci()
		{
			this._tblDersSecims = new EntitySet<tblDersSecim>(new Action<tblDersSecim>(this.attach_tblDersSecims), new Action<tblDersSecim>(this.detach_tblDersSecims));
			this._tblBolum = default(EntityRef<tblBolum>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OgrAdiSoyadi", DbType="NVarChar(50)")]
		public string OgrAdiSoyadi
		{
			get
			{
				return this._OgrAdiSoyadi;
			}
			set
			{
				if ((this._OgrAdiSoyadi != value))
				{
					this.OnOgrAdiSoyadiChanging(value);
					this.SendPropertyChanging();
					this._OgrAdiSoyadi = value;
					this.SendPropertyChanged("OgrAdiSoyadi");
					this.OnOgrAdiSoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OgrNumara", DbType="NVarChar(50)")]
		public string OgrNumara
		{
			get
			{
				return this._OgrNumara;
			}
			set
			{
				if ((this._OgrNumara != value))
				{
					this.OnOgrNumaraChanging(value);
					this.SendPropertyChanging();
					this._OgrNumara = value;
					this.SendPropertyChanged("OgrNumara");
					this.OnOgrNumaraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TcKimlik", DbType="NVarChar(50)")]
		public string TcKimlik
		{
			get
			{
				return this._TcKimlik;
			}
			set
			{
				if ((this._TcKimlik != value))
				{
					this.OnTcKimlikChanging(value);
					this.SendPropertyChanging();
					this._TcKimlik = value;
					this.SendPropertyChanged("TcKimlik");
					this.OnTcKimlikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BolumId", DbType="Int")]
		public System.Nullable<int> BolumId
		{
			get
			{
				return this._BolumId;
			}
			set
			{
				if ((this._BolumId != value))
				{
					if (this._tblBolum.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBolumIdChanging(value);
					this.SendPropertyChanging();
					this._BolumId = value;
					this.SendPropertyChanged("BolumId");
					this.OnBolumIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="NVarChar(250)")]
		public string Adres
		{
			get
			{
				return this._Adres;
			}
			set
			{
				if ((this._Adres != value))
				{
					this.OnAdresChanging(value);
					this.SendPropertyChanging();
					this._Adres = value;
					this.SendPropertyChanged("Adres");
					this.OnAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="NVarChar(50)")]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this.OnTelefonChanging(value);
					this.SendPropertyChanging();
					this._Telefon = value;
					this.SendPropertyChanged("Telefon");
					this.OnTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DogumTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> DogumTarihi
		{
			get
			{
				return this._DogumTarihi;
			}
			set
			{
				if ((this._DogumTarihi != value))
				{
					this.OnDogumTarihiChanging(value);
					this.SendPropertyChanging();
					this._DogumTarihi = value;
					this.SendPropertyChanged("DogumTarihi");
					this.OnDogumTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resim", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Resim
		{
			get
			{
				return this._Resim;
			}
			set
			{
				if ((this._Resim != value))
				{
					this.OnResimChanging(value);
					this.SendPropertyChanging();
					this._Resim = value;
					this.SendPropertyChanged("Resim");
					this.OnResimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KayıtTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> KayıtTarihi
		{
			get
			{
				return this._KayıtTarihi;
			}
			set
			{
				if ((this._KayıtTarihi != value))
				{
					this.OnKayıtTarihiChanging(value);
					this.SendPropertyChanging();
					this._KayıtTarihi = value;
					this.SendPropertyChanged("KayıtTarihi");
					this.OnKayıtTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblOgrenci_tblDersSecim", Storage="_tblDersSecims", ThisKey="Id", OtherKey="OgrId")]
		public EntitySet<tblDersSecim> tblDersSecims
		{
			get
			{
				return this._tblDersSecims;
			}
			set
			{
				this._tblDersSecims.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblBolum_tblOgrenci", Storage="_tblBolum", ThisKey="BolumId", OtherKey="Id", IsForeignKey=true)]
		public tblBolum tblBolum
		{
			get
			{
				return this._tblBolum.Entity;
			}
			set
			{
				tblBolum previousValue = this._tblBolum.Entity;
				if (((previousValue != value) 
							|| (this._tblBolum.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblBolum.Entity = null;
						previousValue.tblOgrencis.Remove(this);
					}
					this._tblBolum.Entity = value;
					if ((value != null))
					{
						value.tblOgrencis.Add(this);
						this._BolumId = value.Id;
					}
					else
					{
						this._BolumId = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblBolum");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblDersSecims(tblDersSecim entity)
		{
			this.SendPropertyChanging();
			entity.tblOgrenci = this;
		}
		
		private void detach_tblDersSecims(tblDersSecim entity)
		{
			this.SendPropertyChanging();
			entity.tblOgrenci = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblOgrtGorevlisi")]
	public partial class tblOgrtGorevlisi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _OgrtAdi;
		
		private string _OgrtSoyadi;
		
		private System.Nullable<int> _DersId;
		
		private EntitySet<tblDersKayit> _tblDersKayits;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnOgrtAdiChanging(string value);
    partial void OnOgrtAdiChanged();
    partial void OnOgrtSoyadiChanging(string value);
    partial void OnOgrtSoyadiChanged();
    partial void OnDersIdChanging(System.Nullable<int> value);
    partial void OnDersIdChanged();
    #endregion
		
		public tblOgrtGorevlisi()
		{
			this._tblDersKayits = new EntitySet<tblDersKayit>(new Action<tblDersKayit>(this.attach_tblDersKayits), new Action<tblDersKayit>(this.detach_tblDersKayits));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OgrtAdi", DbType="NVarChar(50)")]
		public string OgrtAdi
		{
			get
			{
				return this._OgrtAdi;
			}
			set
			{
				if ((this._OgrtAdi != value))
				{
					this.OnOgrtAdiChanging(value);
					this.SendPropertyChanging();
					this._OgrtAdi = value;
					this.SendPropertyChanged("OgrtAdi");
					this.OnOgrtAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OgrtSoyadi", DbType="NVarChar(50)")]
		public string OgrtSoyadi
		{
			get
			{
				return this._OgrtSoyadi;
			}
			set
			{
				if ((this._OgrtSoyadi != value))
				{
					this.OnOgrtSoyadiChanging(value);
					this.SendPropertyChanging();
					this._OgrtSoyadi = value;
					this.SendPropertyChanged("OgrtSoyadi");
					this.OnOgrtSoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DersId", DbType="Int")]
		public System.Nullable<int> DersId
		{
			get
			{
				return this._DersId;
			}
			set
			{
				if ((this._DersId != value))
				{
					this.OnDersIdChanging(value);
					this.SendPropertyChanging();
					this._DersId = value;
					this.SendPropertyChanged("DersId");
					this.OnDersIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblOgrtGorevlisi_tblDersKayit", Storage="_tblDersKayits", ThisKey="Id", OtherKey="OgrtId")]
		public EntitySet<tblDersKayit> tblDersKayits
		{
			get
			{
				return this._tblDersKayits;
			}
			set
			{
				this._tblDersKayits.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblDersKayits(tblDersKayit entity)
		{
			this.SendPropertyChanging();
			entity.tblOgrtGorevlisi = this;
		}
		
		private void detach_tblDersKayits(tblDersKayit entity)
		{
			this.SendPropertyChanging();
			entity.tblOgrtGorevlisi = null;
		}
	}
}
#pragma warning restore 1591
